### ISSUE TITLE
Color For DarkTheme

### ISSUE THREAD

**Issue by takaaptech** [LifeandStyleMedia/InspectorStateMachine#7]
Here you are. Your Plugin looks awesome so far!

![screen shot 2018-10-30 at 10 58 31 am](https://user-images.githubusercontent.com/6276251/47695140-34ad1000-dc33-11e8-95ab-ffd5e07226c6.png)
![screen shot 2018-10-30 at 10 56 36 am](https://user-images.githubusercontent.com/6276251/47695141-3545a680-dc33-11e8-93e6-44756ace4d0d.png)
![screen shot 2018-10-30 at 10 58 46 am](https://user-images.githubusercontent.com/6276251/47695142-3545a680-dc33-11e8-98c2-22f96cf78ef8.png)
![screen shot 2018-10-30 at 11 00 02 am](https://user-images.githubusercontent.com/6276251/47695143-3545a680-dc33-11e8-8936-6c86074e8a09.png)
![screen shot 2018-10-30 at 11 00 32 am](https://user-images.githubusercontent.com/6276251/47695144-3545a680-dc33-11e8-8581-61a7eeb759ce.png)
![screen shot 2018-10-30 at 11 00 43 am](https://user-images.githubusercontent.com/6276251/47695145-35de3d00-dc33-11e8-87e1-a6af367d889c.png)
![screen shot 2018-10-30 at 11 00 10 am](https://user-images.githubusercontent.com/6276251/47695147-35de3d00-dc33-11e8-8e88-d211642c3407.png)

**Comment by JasonJonesLASM** [comment]
Perfect, thank you very much! I'll fix up the colors for next release, probably within a few days along with predefined machines as ScriptableObjects.
